### ISSUE TITLE
html editor

### ISSUE THREAD

**Issue by CathrineDQ** [digiquip/dq-website#108]
Put in place a html editor for adding content(s) to various pages. The content will be different from page to page, and multiple to one page, so need a setup where I can add a lot of different content
Here's a couple of examples:
1. <script src="https://static.elfsight.com/platform/platform.js" async></script>
<div class="elfsight-app-81cbe388-1724-4e56-b24d-e9cbcb69c3f4" data-elfsight-app-lazy></div>
2. <script src="https://static.elfsight.com/platform/platform.js" async></script>
<div class="elfsight-app-ffc7fb08-4ac1-4121-8929-9cb66e965724" data-elfsight-app-lazy></div>

**Comment by CathrineDQ** [comment]
@MZeshanShoukat Hi! I've moved the conversation from Slack to Github :-)

**Comment by MZeshanShoukat** [comment]
Hello @CathrineDQ , to create this widget which allows embedding functionality to other pages, we can create this widget in this digiquip site, or in some another new app.
- we will be need to store the "html generated by the widget in database" so that it can be accessible in the form of embed page 

we can add embed html setup in the same digiquip or we can create a new 'react/angular' app and setup the widget there.
